name: SaaSBox CLI Push
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm test
    # run npm test, build, lint, etc.
    - name: Install saasbox cli
      run: npm install -g saasbox-cli
    - name: Create auth file with secrets
      run: echo "{\"apikey\": \"${{ secrets.SAASBOX_APIKEY }}\", \"appid\": \"${{ secrets.SAASBOX_APPID }}\" }" > ~/sbox.config.json
    - name: Run sbox cli:
      run: sbox-cli -a -d .