name: SaaSBox CLI Push
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    #- run: npm ci
    #- run: npm test
    # run npm test, build, lint, etc.
    - name: Install saasbox cli
      run: npm install -g saasbox-cli
    - name: Create auth file with secrets
      env: 
        SAASBOX_APIKEY: ${{ secrets.SAASBOX_APIKEY}}
        SAASBOX_APPID: ${{ secrets.SAASBOX_APPID }}
      #run: echo "{\"apikey\": \"$SAASBOX_APIKEY\", \"appid\": \"$SAASBOX_APPID\" }" > ~/sbox.config.json
      run: echo "Hello world"
    #- name: Run sbox cli:
    #  run: saasbox-cli -a -d .